### ISSUE TITLE
Raw Images

### ISSUE THREAD

**Issue by robotsorcerer** [crigroup/ensenso#14]
Hey,

I am testing the N35 version of the sensor. Before I go ahead and try out your code, I wanted to be sure that your code gives RGB images e.g. in CV_8UC3 format? 

I see that you have an indicator function that tests for `CV_8UC3` in your `ensenso_node.cpp`. It is not clear from your code as you only publish `camera info` messages and raw single channel ir `CV_8UC1` images.

I would be glad to know.

**Comment by fsuarez6** [comment]
@lakehanne AFAIK the N35 camera doesn't provide RGB images. [From the manual](http://www.ensenso.com/manual/index.html?_cameras_byserialno_$stereoserial_images_raw_left.htm):

> **Format:** A one channel image of unsigned 8bit values containing the raw camera image.

**Comment by robotsorcerer** [comment]
Thanks! Closing then!

**Comment by robotsorcerer** [comment]
One more thing, does your API generate the so called [PointMap](http://www.ensenso.com/manual/index.html?cmdcomputepointmap.htm)?

**Comment by fsuarez6** [comment]
Yes, we use the [PointMap to generate the point cloud](https://github.com/crigroup/ensenso/blob/kinetic-devel/src/ensenso_grabber.cpp#L677).\
The driver [publishes the point cloud](https://github.com/crigroup/ensenso/blob/kinetic-devel/src/ensenso_driver.cpp#L86) in the `depth/points` topic.
