### ISSUE TITLE
Triggering camera via software

### ISSUE THREAD

**Issue by eric-tc** [crigroup/ensenso#20]
Hi there is a way to acquire image only when a request is made. For example now when i start the Ensenso driver node the streaming is continuous but i want to acquire a single point cloud using a trigger, because in the continuous streaming there is a lot of load on CPU?.
Thanks

**Comment by fsuarez6** [comment]
You can use the [`EnsensoDriverReconfigure.enable_streaming`](https://github.com/crigroup/ensenso/blob/kinetic-devel/src/ensenso/snatcher.py#L46) to enable/disable the streaming of the point cloud and/or the images

The [snapshooter.py](https://github.com/crigroup/ensenso/blob/kinetic-devel/scripts/snapshooter.py) may be a good example:
```
$ rosrun ensenso snapshooter.py -h
usage: snapshooter.py [-h] [--snapshots SNAPSHOTS] [--exposure EXPOSURE]
                      [--light] [--debug]

Snapshooter script

optional arguments:
  -h, --help            show this help message and exit
  --snapshots SNAPSHOTS
                        Number of snapshots to be taken, (default=2)
  --exposure EXPOSURE   Exposure time in seconds, (default=1.0)
  --light               If set, will enable the front light for the camera
                        snapshots
  --debug               If set, will show additional debugging messages
```
MWE:
```
$ roslaunch ensenso viewer.launch rqt:=False rviz:=False
$ rosrun ensenso snapshooter.py _ns:=camera
```

**Comment by eric-tc** [comment]
Hi, 
thanks for the answer but making some tests i have seen that when you exectue "ensenso_ptr_->start()" there is a very high load on cpu and in my application i have different cameras so i have to save much more computational resource as possibile.
So when i execute roslaunch ensenso viewer.launch rqt:=False rviz:=False my computer have a very high computational load.
I have resolved the problem by making another service to start and stop the camera by change directly the code in ensenso_driver.cpp at line 105. 
Do you think could be a good idea for saving computational resources?

Thanks

**Comment by fsuarez6** [comment]
Yes, in that scenario it makes sense to remove the `ensenso_ptr_->start()` you mention.
You don't need a service to start/stop the camera. You can use the dynamic reconfigure parameters.

**Comment by eric-tc** [comment]
Ok thanks for the info.
Is there an automatic extrinsic calibration procedure in your package?
Thanks

**Comment by fsuarez6** [comment]
No. For extrinsic calibration we use the tool provided by ensenso:
https://www.ensenso.com/manual/calibrating_a_camera.htm
I'm closing this given that the initial issue, 'Triggering camera via software', has been addressed.
